# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Player.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.QtCore import QUrl
from PyQt5.QtMultimedia import QMediaContent
from PyQt5 import QtCore, QtWidgets, QtMultimedia
from PyQt5.QtWidgets import QFileDialog

file=""
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("MySimplePlayer")
        Dialog.resize(937, 616)
        self.widget = QVideoWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 20, 891, 491))
        self.widget.setObjectName("widget")
        self.Play = QtWidgets.QPushButton(Dialog)
        self.Play.setGeometry(QtCore.QRect(50, 550, 93, 28))
        self.Play.setObjectName("Play")
        self.openFile = QtWidgets.QPushButton(Dialog)
        self.openFile.setGeometry(QtCore.QRect(160, 550, 93, 28))
        self.openFile.setObjectName("openFile")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("MySimplePlayer", "MySimplePlayer"))
        self.Play.setText(_translate("MySimplePlayer", "Play"))
        self.openFile.setText(_translate("MySimplePlayer", "Open File"))

from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtMultimedia import QMediaContent

class Window(QtWidgets.QMainWindow):
    def __init__(self):
        super(Window, self).__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        self.media= QtMultimedia.QMediaPlayer(self)
        self.media.setVideoOutput(self.ui.widget)
        self.ui.Play.clicked.connect(self.Plays)
        self.ui.openFile.clicked.connect(self.Open)

    def Open(self):
        file=QFileDialog.getOpenFileName(self, "Выберите файл видео",
                ".", "Video Files (*.mp4 *.fIv *.ts *.mts *.avi)") 
        print(file[0]) 
        if file:
            self.media.setMedia(QMediaContent(QUrl.fromLocalFile(file[0]))) 
            self.media.play()

    def Plays(self):
        url = QtCore.QUrl(file[0])
        self.media.setMedia(QtMultimedia.QMediaContent(url)) 
        self.media.play()

app = QtWidgets.QApplication([])
applicatin = Window()
applicatin.show()
sys.exit(app.exec())